### ISSUE TITLE
Support Angular 6 and RxJS 6

### ISSUE THREAD

**Issue by euangoddard** [jsdevtom/take-until-destroy#10]
Since Angular's upgrade to version 6 they require RxJS version 6. The current codebase uses RxJS 5.5.2 and so we need to use rxjs-compat in order to use this package.

I'd happily make a PR for this change as it's straight-forward except that there are a lot of dependencies that I'm unsure of in package.json

**Comment by jsdevtom** [comment]
Please make the pull request! :+1:

**Comment by euangoddard** [comment]
Done: https://github.com/jsdevtom/take-until-destroy/pull/11

**Comment by jsdevtom** [comment]
Thank you @euangoddard :tada:
