### ISSUE TITLE
Breaks browsers that does not support ES6

### ISSUE THREAD

**Issue by sagilevi** [jsdevtom/take-until-destroy#8]
When installing this package, version 1.3.0, with NPM, the file dist/take-until-destroy.js contains usage of arrow functions in line 46, which causes browsers that does not support ES6 (e.g. IE11) to break. Packages should contain compiled code that would not break browsers like IE11.

**Comment by jsdevtom** [comment]
Hi @sagilevi you are absolutely correct. I am really busy right now. Create a pull request if you want

**Comment by sagilevi** [comment]
I think the solution is to change the target from "es6" to "es5" in tsconfig.json line 3

**Comment by sagilevi** [comment]
@jsdevtom Can you publish this change please?
Thanks!

**Comment by jsdevtom** [comment]
This is now done

**Comment by jsdevtom** [comment]
@sagilevi @AlteredConstants  Thanks!
